# Generated by Django 4.2.16 on 2024-10-15 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fotografica',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
