# Generated by Django 4.2.16 on 2024-10-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_fotografica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_fotografica',
            new_name='data_fotografia',
        ),
    ]
