# Generated by Django 4.2.16 on 2024-10-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_rename_data_fotografica_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='foto',
            new_name='foto_old',
        ),
    ]
