# Generated by Django 4.2.16 on 2024-10-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_rename_foto_fotografia_foto_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
